FROM ghcr.io/astral-sh/uv:python3.14-trixie
ENV HF_HOME=/models
ENV HF_HUB_DISABLE_SYMLINKS_WARNING=1
ENV TRANSFORMERS_CACHE=/models

RUN uv pip install --system \
    torch==2.11.0+cu128 \
    torchvision==0.26.0+cu128 \
    --index-url https://download.pytorch.org/whl/cu128

RUN uv pip install --system \
    surya-ocr==0.17.1 \
    transformers==4.56.1

RUN python - <<EOF
from surya.foundation import FoundationPredictor
from surya.detection import DetectionPredictor
from surya.layout import LayoutPredictor
from surya.recognition import RecognitionPredictor
from surya.table_rec import TableRecPredictor

fp = FoundationPredictor()
DetectionPredictor()
LayoutPredictor(fp)
RecognitionPredictor(fp)
TableRecPredictor()
EOF
